---

#To install pip and the AWS CLI
- name: epel realse 
  get_url: 
    url: http://fedora-epel.mirrors.tds.net/fedora-epel//epel-release-latest-7.noarch.rpm
    dest: /home/ec2-user/
 
- name: install rpm
  shell: rpm -ivh epel-release-latest-7.noarch.rpm
   
- name : python pip
  yum : 
   name :  python-pip
   state : present 
   update_cache: yes

- name : Install awscli
  pip :
   name : awscli
