---
- name : Synsc S3
  shell : aws s3 sync s3://"{{ bucket_name }}" "{{ pathtocopybucketfiles }}" --delete
  environment:
   AWS_ACCESS_KEY_ID : "{{ awsaccesskeyid }}"
   AWS_SECRET_ACCESS_KEY : "{{ awssecretaccesskey }}"
   AWS_DEFAULT_REGION : "{{ region }}"
    
